version: '3'
services:
  web: 
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    tty: true
    ports:
      - 83:80
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - ./laravel:/var/www/html/laravel
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
    - db

  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/dump:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf # Передаем в контейнер конфигурационный файл
    # command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3399:3306
    # healthcheck:
    #   test: [ "CMD", "mysqladmin", "ping" ]

  node:
    build:
      context: ./docker/nodejs
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
        - "5173:5173"
    container_name: node
    volumes:
      - ./laravel:/var/www/html/laravel

volumes:
  # Чтобы данные БД не пропадали после выключения создаем именованный том
  db_data:
    driver: local